Import("env")
import os
import random

# Use the PlatformIO environment to find the project directory.
project_dir = env['PROJECT_DIR']
include_dir = os.path.join(project_dir, 'include')
os.makedirs(include_dir, exist_ok=True)

# Generate 6 random bytes for the MAC address
mac = [random.randrange(0, 256) for _ in range(6)]
msb_bytes = ', '.join('0x{:02x}'.format(b) for b in mac)
lsb_bytes = ', '.join('0x{:02x}'.format(b) for b in reversed(mac))

# create an ASCII hex serial (uppercase) from MSB bytes, two chars per byte
hex_chars = ''.join('{:02X}'.format(b) for b in mac)
serial_chars = ','.join("'{}'".format(c) for c in hex_chars)
serial_len = len(hex_chars)

content = (
    '/* This file is autogenerated by generate_compiletime_mac.py */\n'
    '#ifndef COMPILE_TIME_MAC_H\n'
    '#define COMPILE_TIME_MAC_H\n\n'
    '/* Provide the MAC bytes in conventional order (MSB first): */\n'
    '#define COMPILE_TIME_MAC_MSB_BYTES ' + msb_bytes + '\n\n'
    '/* Provide the MAC bytes in LSB-first order (reversed) */\n'
    '#define COMPILE_TIME_MAC_LSB_BYTES ' + lsb_bytes + '\n\n'
    '/* USB serial derived from the MAC (ASCII hex, MSB first) */\n'
    '#define USB_CFG_SERIAL_NUMBER ' + serial_chars + '\n'
    '#define USB_CFG_SERIAL_NUMBER_LEN ' + str(serial_len) + '\n\n'
    '/* (previously provided a generated marker macro; removed per request) */\n'
    '#endif /* COMPILE_TIME_MAC_H */\n'
)

header_path = os.path.join(include_dir, 'compile_time_mac.h')
with open(header_path, 'w') as f:
    f.write(content)

print('Wrote compile-time MAC to', header_path)
